# Fill it with appropiate values, then 
# Save this file as '_config.deploy.yml'
# The file will not included on the git repo for security reasons.
deploy:
  type: ftpsync
  host: hodoandmarie.com
  user: xxxxxx
  pass: xxxxxx
  remote: web
  port: 21
  verbose: false