pipelines:
  default:
    - step:
        script:
          - echo 'I push has been made to the repo!'
  branches:
    deploy:
      - step:
          script:
            - echo 'Starting deploy process'