pipelines:
  default:
    - step:
        script:
          - echo 'I push has been made to the repo!'
  branches:
    deploy:
      - step:
          name: Build and test
          deployment: production
          script:
            - echo 'Starting deployment process'
            - npm install -g hexo
            - npm install 
            - hexo generate            