# Bitbucket pipelines file
# ------------------------
#
# v. 1.0.0
#
# We use pipelines to upload the website to the production server.
# Each time someone pushes to the branch called 'deploy'.
#
# The website is generated and deployed using FTP.
# The credentials are stored on variables that can be set 
# through the Bitbucket page of this repo:
# > bitbucket.org/factsandfictions/hodoandmarie-site
#
# @todo: send and email once its done
# 
#
image: node:10.16.0
pipelines:
  branches:
    deploy:
      - step:
          name: Build 
          deployment: production
          script:
            - echo 'Starting deployment process'
            - npm install -g hexo
            - npm install 
            - hexo generate
            - pipe: atlassian/ftp-deploy:0.1.0
              variables: 
                USER: $FTP_USER
                PASSWORD: $FTP_PASS
                SERVER: $FTP_HOST
                REMOTE_PATH: $FTP_REMOTE
                LOCAL_PATH: 'public'
                DEBUG: 'TRUE' 