image: node:10.16.0
pipelines:
  default:
  branches:
    deploy:
      - step:
          name: Build 
          deployment: production
          script:
            - echo 'Starting deployment process'
            - npm install -g hexo
            - npm install 
            - hexo generate
            - pipe: atlassian/ftp-deploy:0.1.0
              variables: 
                USER: $FTP_USER
                PASSWORD: $FTP_PASS
                SERVER: $FTP_HOST
                REMOTE_PATH: $FTP_REMOTE
                LOCAL_PATH: 'public'
                DEBUG: 'TRUE' 
            - 